name: PR Checks

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - uses: actions/setup-node@v3
        with:
          node-version:
          cache: 'pnpm'

      - run: pnpm install

      # - name: Comment outdated dependencies on PR
      #   id: outdated
      #   run: |
      #     echo 'outdated<<EOF' >> $GITHUB_OUTPUT
      #     pnpm outdated --format json >> "$GITHUB_OUTPUT" || true
      #     echo 'EOF' >> $GITHUB_OUTPUT

      - name: Comment outdated dependencies, typecheck and lint on PR
        uses: actions/github-script@v7
        # env:
        #   OUTDATED: ${{ steps.outdated.outputs.outdated }}
        with:
          script: |
            let body = "";
          
            const execOut = await exec.getExecOutput("pnpm", ["outdated", "--json"], { ignoreReturnCode: true });
            if (!execOut.exitCode || !execOut.stdout || execOut.stdout === '{}') {
              body = "## ✅ Dependencies\n\nAll dependencies are up to date.";
            } else {              
              const packages = Object.entries(JSON.parse(execOut.stdout));
              if (packages.length === 0) {
                body = `## ⚠️ Outdated Dependencies Detected\n
                Found **${packages.length}** outdated package${packages.length > 1 ? 's' : ''}:\n
                | Package | Current | Wanted | Latest | Type |
                |---------|---------|--------|--------|------|\n`

                for (const [pkg, info] of packages)
                  body += `| ${pkg} | ${info.current || '-'} | ${info.wanted || '-'} | ${info.latest || '-'} | ${info.dependencyType || '-'} |\n`;

                body += "\n---\n*Run `pnpm outdated` locally for more details or `pnpm update` to update dependencies.*";
              }
            }            

            const results = await (new (require("eslint")).ESLint()).lintFiles(".");
            let lintFiles = 0;
            let lintErrors = 0;
            let lintWarnings = 0;
            let eslintBody = "";
            const severityIcons = ["ℹ️", "⚠️", "‼️"];

            for (const result of results) {
              if (result.errorCount || result.warningCount) {
                lintFiles += 1;
                lintErrors += result.errorCount;
                lintWarnings += result.warningCount;
                eslintBody += `* ${result.filePath}\n\n`;
                for (const m of result.messages) eslintBody += `  * ${m.line}:${m.column} ${severityIcons[m.severity]} ${m.ruleId || ""} ${m.message}\n`;
              }
            }

            if (lintFiles === 0) body += "## ✅ ESLint\n\nNo problems found.";
            else body += `## ⚠️ ESLint Issues\n
            Found **${lintErrors}** error${lintErrors !== 1 ? "s" : ""} \
            and **${lintWarnings}** warning${lintWarnings !== 1 ? "s" : ""} \
            across **${lintFiles}** file${lintFiles !== 1 ? "s" : ""}.\n
            ${eslintBody}\n---\n*Run \`pnpm lint --fix\` to attempt automatic fixes or review issues manually.*`;

            await core.summary.addRaw(body).write();

            await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body
              });


      - run: |
          echo "## Typecheck" >> $GITHUB_STEP_SUMMARY
          pnpm tsc >> "$GITHUB_STEP_SUMMARY"
        continue-on-error: true
        