name: PR Checks

on: pull_request

jobs:
  check:
    runs-on: ubuntu-latest
    steps:    
      - uses: pnpm/action-setup@v4
        with:
          version: 10

      - name: Comment outdated dependencies on PR
        run: |
            echo 'outdated<<EOF' >> $GITHUB_OUTPUT
            pnpm outdated --format json >> "$GITHUB_OUTPUT" || true
            echo 'EOF' >> $GITHUB_OUTPUT
        continue-on-error: true

      - name: Generate list using Markdown
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
          pnpm outdated >> $GITHUB_STEP_SUMMARY
      

          
